print("... you probably know it already.")
import turtle
scren = turtle.Screen()
scren.setup(width=600, height=400)

jim = turtle.Turtle()
jim.color("Yellow")
jim.forward(100)
jim.left(45)
jim.forward(100)
jim.color("Black")
jim.forward(50)
jim.left(90)
jim.forward(50)
jim.left(90)
jim.forward(50)
jim.left(90)
jim.forward(50)

pippey=turtle.Turtle()
pippey.color("Yellow")
pippey.left(135)
pippey.forward(100)
pippey.right(90)
pippey.forward(50)
pippey.right(90)
pippey.forward(50)
pippey.left(45)
pippey.forward(100)
pippey.left(45)
pippey.forward(50)

jim.penup()
jim.right(45)
jim.forward(100)
jim.right(90)
jim.forward(50)
jim.write("bnana")

scren.mainloop()